name: flutter_places_autocomplete
description: A Google Places API plugin to get the autocomplete locations for user's input with the geolocation.
version: 0.2.0
homepage: https://github.com/marciowelben/flutter_places_autocomplete
maintainer: Marcio Montenegro (@marciowelben)
author: Marcio Montenegr <marcio.montenegro@gmail.com>
environment:
  sdk: '>=2.1.0 <3.0.0'
  flutter: '>=1.10.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  mockito: ^4.1.1
  equatable: ^1.0.2
  http: ^0.12.0+4
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_places_autocomplete
        pluginClass: FlutterPlacesAutocompletePlugin
      ios:
        pluginClass: FlutterPlacesAutocompletePlugin
